name: build-and-test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Set up CMake 3.18
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: 3.18

      - name: Build
        run: |
            cmake -D CXXP_ENABLE_TESTING=ON -B build -S .
            cmake --build build --config $BUILD_TYPE

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -V -C $BUILD_TYPE
