name: codecov

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up CMake 3.18
      uses: jwlawson/actions-setup-cmake@v1.8
      with:
        cmake-version: 3.18

    - name: Install GCC 11
      run: |
          sudo apt-get install gcc-11 g++-11

    - name: Build
      run: |
        cmake -D CMAKE_BUILD_TYPE=$BUILD_TYPE -D CXXP_ENABLE_COVERAGE=ON -B build -S .
        cmake --build build --config $BUILD_TYPE
      env:
        CC: gcc-11
        CXX: g++-11

    - name: Run tests
      working-directory: ${{github.workspace}}/build
      run: ctest -V -C $BUILD_TYPE

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        working-directory: ${{github.workspace}}/build
        fail_ci_if_error: true
